name: Norminette Check

on:
  pull_request:
    branches: [ main, master, dev ]

jobs:
  check_norm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: Run Norminette
        run: |
          norminette